server:
  port: 10000 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-core # 服务名
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/20220322_sys?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root


mybatis-plus: #mybatis
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/wcw/sys/mapper/xml/*.xml

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    keyId: LTAI5t628voexyyx3AMgC6JT
    keySecret: 97VN2Hqsv5kN84bAkxl9GJfjxc2ANi
    bucketName: 230119blog

  vod:
    keyid: LTAI5t628voexyyx3AMgC6JT
    keysecret: 97VN2Hqsv5kN84bAkxl9GJfjxc2ANi